spring.application.name=backend
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=bRWNgQmFwJkNzJiSQqZTFmrzaSpvvCqE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=disable
spring.security.user.password=disable
spring.security.enabled=false
server.port=${PORT:8080}