spring.application.name=backend 
spring.datasource.url=jdbc:mysql://localhost:3306/bharatmesh
spring.datasource.username=root
spring.datasource.password=Advik@1424
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=disable
spring.security.user.password=disable
spring.security.enabled=false